rg_name         = "OXZRGOXHD01"
environment     = "develop"
applicationName = "PORTAL"
location        = "South Central US"
short_company   = "OX"
short_cloud     = "Z"
short_project   = "OXH"
short_env       = "D"